### ISSUE TITLE
Compile error :: lib dependencies problems

### ISSUE THREAD

**Issue by brokerexio** [heptacoin/heptacoin#3]
I double checked all lib requirements but I keep with the following error:
```
libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `boost::thread::do_try_join_until(boost::detail::mono_platform_timepoint const&)':
httpserver.cpp:(.text._ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE[_ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE]+0x9f): undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
collect2: error: ld returned 1 exit status
```
Are you missing to document some extra lib?

**Comment by Nibirugroup** [comment]
RUN \
  wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium-dev_1.0.13-1_amd64.deb &&\
  wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.13-1_amd64.deb &&\
  dpkg -i libsodium*deb

**Comment by heptacoin** [comment]
Yes, sorry! 
libsodium is also required to build. 

`sudo apt-get install libsodium-dev`

I update the documentation in few minutes.
Thanks for the feedback

**Comment by heptacoin** [comment]
Fixed. https://github.com/heptacoin/heptacoin/commit/1784457fcc2b19797bc0663793dd1009a38ada60
