### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by brokerexio** [heptacoin/heptacoin#4]
Ubuntu 16LTS. libsodium and boost(1.67) are the lastest version
It hepta compiled with  boost 1.64?
```
  CXXLD    heptacoind
libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `boost::thread::do_try_join_until(boost::detail::mono_platform_timepoint const&)':
httpserver.cpp:(.text._ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE[_ZN5boost6thread17do_try_join_untilERKNS_6detail23mono_platform_timepointE]+0x9f): undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
```

**Comment by heptacoin** [comment]
Yes 1.64. You need to compile with boost provided with OS.

`sudo apt-get install libboost-all-dev
`

Or you can just download and install Heptacoin Core from the binary distribution: https://github.com/heptacoin/heptacoin/releases

**Comment by brokerexio** [comment]
Ok. I have Ubuntu 16LTS with all. It reports the same problem cited before.
Do you have a docker image?
Do you tested with boost 1.67?
